apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aurora-system

resources:
- base/namespace.yaml
- base/serviceaccount.yaml
- base/rbac.yaml
- crds/mltrainingjob.yaml
- crds/mldeployment.yaml
- mlflow/mlflow-deployment.yaml
- mlflow/mlflow-service.yaml
- inference/inference-deployment.yaml
- inference/inference-canary.yaml
- inference/inference-ingress.yaml
- storage/ceph-object-user.yaml
- storage/mlflow-bucket-job.yaml

secretGenerator:
- name: aurora-s3-creds
  namespace: aurora-system
  literals:
  - AWS_ACCESS_KEY_ID=placeholder
  - AWS_SECRET_ACCESS_KEY=placeholder
  options:
    disableNameSuffixHash: true

configMapGenerator:
- name: mlflow-config
  namespace: aurora-system
  literals:
  - MLFLOW_S3_ENDPOINT_URL=http://rook-ceph-rgw-mlflow-store.rook-ceph.svc.cluster.local:80
  - AWS_S3_FORCE_PATH_STYLE=true
  - MLFLOW_S3_IGNORE_TLS=true
  - AWS_DEFAULT_REGION=us-east-1
